### ISSUE TITLE
It looks like SASxport does not support multiple data frames in one xport file.

### ISSUE THREAD

**Issue by rogerjdeangelis** [MangoTheCat/SASxport#8]
Thanks for the very useful package

Minor issue that is easily worked around using multiple output V5 transport files.
It looks like SASxport does not support multiple dataframes in one xport file.

%utl_submit_r64('
library(SASxport);
library(Hmisc);
d1 <- data.frame(y1=c(1,2,3),y2=c(4,5,6));
d2 <- data.frame(y1=c(3,2,1),y2=c(6,5,4));
my.list <- list(d1, d2);
str(my.list);
write.xport(my.list,file="d:/xpt/want.xpt");
');

List of 2
 $ :'data.frame':	3 obs. of  2 variables:
  ..$ y1: num [1:3] 1 2 3
  ..$ y2: num [1:3] 4 5 6
 $ :'data.frame':	3 obs. of  2 variables:
  ..$ y1: num [1:3] 3 2 1
  ..$ y2: num [1:3] 6 5 4

Error in write.xport(my.list, file = "d:/xpt/want.xpt") :
  ' my.list ' is not a data.frame object.
Execution halted

**Comment by owenjonesuob** [comment]
Hi @rogerjdeangelis!

You can provide multiple dataframes to the `write.xport` function in 2 different ways.

Either pass in multiple unnamed arguments:
```
write.xport(d1, d2, file = "example.xpt")
```
Or pass in a list of dataframes as a parameter called `list`:
```
my_list <- list(d1, d2)
write.xport(list = my_list, file = "example.xpt")
```
I've adjusted the documentation for the next release so that this is made a bit clearer.

Best wishes, Owen
